// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmpbmlkkfwvuivxrstdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcGJtbGtrZnd2dWl2eHJzdGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzgzNzIsImV4cCI6MjA2OTUxNDM3Mn0.BXP2ONND3r_9rVSUtvEX94NbMVUjRKmKaFdO1xtGlGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});